version: "3.5"
services:
  nginx:
    volumes: ['./:/var/www/html']
    environment:
      NGINX_PUBLIC: /public
      NGINX_TEMPLATE: application.conf
    depends_on:
      - php-fpm

  php-fpm:
    hostname: "${WARDEN_ENV_NAME}-php-fpm"
    build:
      context: ./.warden/.docker/
      args:
        PHP_VERSION: "${PHP_VERSION:-8.0}"
    environment:
      - TRAEFIK_DOMAIN
      - TRAEFIK_SUBDOMAIN
      - COMPOSER_MEMORY_LIMIT=-1
    volumes: ['./:/var/www/html']
    extra_hosts:
      - ${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
      - ${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}

  php-debug:
    hostname: "${WARDEN_ENV_NAME}-php-debug"
    build:
      context: ./.warden/.docker/debug/
      args:
        PHP_VERSION: "${PHP_VERSION:-8.0}"
    environment:
      - TRAEFIK_DOMAIN
      - TRAEFIK_SUBDOMAIN
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK_PATH_ENV:-/tmp/ssh-auth.sock}
      - NODE_VERSION=${NODE_VERSION:-10}
      - COMPOSER_VERSION=${COMPOSER_VERSION:-1}
      - COMPOSER_MEMORY_LIMIT=-1
      - PHP_IDE_CONFIG=serverName=${WARDEN_ENV_NAME}-docker
      - HISTFILE=/bash_history/.bash_history
      - CHOWN_DIR_LIST=${CHOWN_DIR_LIST:-}
    volumes: ['./:/var/www/html']
    extra_hosts:
      - ${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
      - ${TRAEFIK_SUBDOMAIN:-app}.${TRAEFIK_DOMAIN}:${TRAEFIK_ADDRESS:-0.0.0.0}
    depends_on:
      - php-fpm

  db:
    hostname: "${WARDEN_ENV_NAME}-postgres"
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes: ['./.postgres:/var/lib/postgresql/data']
